# Generated by Django 4.0.5 on 2022-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=128, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=128, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=128, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=128, verbose_name='state or province'),
        ),
    ]
