# Generated by Django 4.0.5 on 2022-11-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_backend.company')),
            ],
            options={
                'verbose_name': 'beneficiary',
                'verbose_name_plural': 'beneficiaries',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.ManyToManyField(related_name='agents', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='agents_companies',
            field=models.ManyToManyField(related_name='cstr_booking_agents', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='operators_companies',
            field=models.ManyToManyField(related_name='cstr_booking_operators', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payers_companies',
            field=models.ManyToManyField(related_name='cstr_booking_payers', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='providers_companies',
            field=models.ManyToManyField(related_name='cstr_booking_providers', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recipients_companies',
            field=models.ManyToManyField(related_name='cstr_booking_recipients', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='requesters_companies',
            field=models.ManyToManyField(related_name='cstr_booking_requesters', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='operator',
            name='company',
            field=models.ManyToManyField(related_name='operators', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='payer',
            name='company',
            field=models.ManyToManyField(related_name='payers', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.ManyToManyField(related_name='providers', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='companies',
            field=models.ManyToManyField(related_name='recipients', through='core_backend.Beneficiary', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='requester',
            name='company',
            field=models.ManyToManyField(related_name='requesters', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_backend.recipient'),
        ),
        migrations.AddField(
            model_name='event',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='events', to='core_backend.beneficiary'),
        ),
    ]
