# Generated by Django 4.0.5 on 2022-07-20 16:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126, verbose_name='name')),
                ('type', models.CharField(max_length=126, verbose_name='type')),
                ('send_method', models.CharField(max_length=126, verbose_name='send method')),
                ('on_hold', models.BooleanField(verbose_name='on hold')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='fax number')),
                ('address', models.CharField(blank=True, max_length=126, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=126, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=126, verbose_name='state or province')),
                ('country', models.CharField(blank=True, max_length=126, verbose_name='country')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='ZIP code')),
            ],
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'agent data'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'consumer data'},
        ),
        migrations.AlterModelOptions(
            name='payer',
            options={'verbose_name': 'payer data'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'provider data'},
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=126, verbose_name='type')),
                ('code', models.CharField(max_length=126, verbose_name='code')),
                ('certificant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core_backend.provider')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core_backend.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core_backend.contact', verbose_name='contact'),
        ),
    ]
