# Generated by Django 4.0.5 on 2022-07-21 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0002_company_contact_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=128, verbose_name='state or province')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='country')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='ZIP code')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'agent data', 'verbose_name_plural': 'agent data'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'bill', 'verbose_name_plural': 'bills'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'consumer data', 'verbose_name_plural': 'consumer data'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='payer',
            options={'verbose_name': 'payer data', 'verbose_name_plural': 'payer data'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'provider data', 'verbose_name_plural': 'provider data'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'rule', 'verbose_name_plural': 'rules'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zip',
        ),
        migrations.AddField(
            model_name='case',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='url',
            field=models.CharField(blank=True, max_length=2048, verbose_name='video URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_backend.contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='code',
            field=models.CharField(max_length=128, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(max_length=128, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='send_method',
            field=models.CharField(max_length=128, verbose_name='send method'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(max_length=128, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_backend.contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core_backend.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='core_backend.location'),
        ),
    ]
