# Generated by Django 4.0.5 on 2022-11-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0003_historicaluser_historicalrequester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core_backend.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.business'),
        ),
    ]
