# Generated by Django 4.0.5 on 2022-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0004_booking_business_historicalbooking_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='companies',
            field=models.ManyToManyField(related_name='bookings', to='core_backend.company'),
        ),
    ]
