# Generated by Django 4.0.5 on 2022-07-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0004_service_description_user_national_id_user_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='national ID')),
                ('ssn', models.CharField(blank=True, max_length=50, verbose_name='social security number')),
                ('role', models.CharField(max_length=128, verbose_name='role')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_backend.contact')),
            ],
            options={
                'verbose_name': 'additional party',
                'verbose_name_plural': 'additional parties',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_parties', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_parties', to='core_backend.additionalparty')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='core_backend.consumer')),
            ],
            options={
                'verbose_name': 'claim',
                'verbose_name_plural': 'claims',
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('agent_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='clinic_staff', serialize=False, to='core_backend.agent')),
            ],
            options={
                'verbose_name': 'clinic staff',
                'verbose_name_plural': 'clinic staves',
            },
            bases=('core_backend.agent',),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('payer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_backend.payer')),
            ],
            options={
                'verbose_name': 'insurance carrier',
                'verbose_name_plural': 'insurance carriers',
            },
            bases=('core_backend.payer',),
        ),
        migrations.CreateModel(
            name='Interpreter',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_backend.provider')),
            ],
            options={
                'verbose_name': 'interpreter',
                'verbose_name_plural': 'interpreters',
            },
            bases=('core_backend.provider',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('consumer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_backend.consumer')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
            bases=('core_backend.consumer',),
        ),
        migrations.AddField(
            model_name='case',
            name='observations',
            field=models.CharField(blank=True, max_length=256, verbose_name='observations'),
        ),
        migrations.DeleteModel(
            name='InterpreterCase',
        ),
        migrations.AddField(
            model_name='event',
            name='claims',
            field=models.ManyToManyField(related_name='events', to='core_backend.claim'),
        ),
    ]
