# Generated by Django 4.0.5 on 2022-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0005_booking_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agents_companies',
            field=models.ManyToManyField(blank=True, related_name='cstr_booking_agents', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='core_backend.category'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='operators_companies',
            field=models.ManyToManyField(blank=True, related_name='cstr_booking_operators', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payers_companies',
            field=models.ManyToManyField(blank=True, related_name='cstr_booking_payers', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='providers_companies',
            field=models.ManyToManyField(blank=True, related_name='cstr_booking_providers', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='recipients_companies',
            field=models.ManyToManyField(blank=True, related_name='cstr_booking_recipients', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requesters_companies',
            field=models.ManyToManyField(blank=True, related_name='cstr_booking_requesters', to='core_backend.company'),
        ),
    ]
