# Generated by Django 4.0.8 on 2022-12-13 18:10

from django.db import migrations, models


def make_m2m(apps, schema_editor):
    User = apps.get_model('core_backend', 'User')
    Company = apps.get_model('core_backend', 'Company')

    for u in User.objects.all():
        if u.contact:
            u.contacts.add(u.contact)

    for c in Company.objects.all():
        if c.contact:
            c.contacts.add(c.contact)
        if c.location:
            c.locations.add(c.location)


def undo_m2m(apps, schema_editor):
    User = apps.get_model('core_backend', 'User')
    Company = apps.get_model('core_backend', 'Company')

    objs = []
    for u in User.objects.all():
        u.contact = u.contacts.all().first()
        objs.append(u)
    User.objects.bulk_update(objs, ['contact'])

    objs.clear()
    for c in Company.objects.all():
        c.contact = c.contacts.all().first()
        c.location = c.locations.all().first()
        objs.append(c)
    Company.objects.bulk_update(objs, ['contact', 'location'])


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0006_alter_booking_agents_companies_and_more'),
    ]

    field_removal_operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]

    field_addition_operations = [
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='core_backend.contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='owner', to='core_backend.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='core_backend.contact'),
        ),
    ]

    operations = [
        *field_addition_operations,
        migrations.RunPython(code=make_m2m, reverse_code=undo_m2m),
        *field_removal_operations,
    ]
