# Generated by Django 4.0.8 on 2023-01-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0007_make_company_location_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='billing amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='bill_rate',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=32, verbose_name='billing rate in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='bill_type',
            field=models.CharField(choices=[('MIN', 'per minute'), ('DAY', 'daily')], default='MIN', max_length=3),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='amount')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core_backend.booking')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
            },
        ),
    ]
