# Generated by Django 4.0.8 on 2023-01-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0008_affiliation_is_deleted_agent_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
