# Generated by Django 4.0.8 on 2023-02-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0008_service_bill_amount_service_bill_rate_and_more'),
        ('core_backend', '0009_business_is_deleted_category_is_deleted_and_more'),
    ]

    operations = [
    ]
