# Generated by Django 4.0.8 on 2023-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0010_merge_20230202_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
