# Generated by Django 4.0.8 on 2023-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0011_expense_is_deleted_historicalexpense_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default='Type A', max_length=128, verbose_name='type'),
        ),
    ]
