# Generated by Django 4.0.8 on 2023-02-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0011_expense_is_deleted_historicalexpense_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='description'),
            preserve_default=False,
        ),
    ]
