# Generated by Django 4.0.8 on 2023-02-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0012_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
    ]
