# Generated by Django 4.0.8 on 2023-02-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0012_category_description'),
        ('core_backend', '0013_remove_service_type'),
    ]

    operations = [
    ]
