# Generated by Django 4.0.5 on 2023-02-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0014_merge_20230213_1414'),
        ('core_backend', '0014_merge_20230215_1308'),
    ]

    operations = [
    ]
