# Generated by Django 4.0.8 on 2023-02-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0014_merge_20230215_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
