# Generated by Django 4.0.8 on 2023-02-28 18:02

import core_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0016_historicaluser_date_of_birth_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core_backend.models.CoreUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='extra',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
