# Generated by Django 4.0.8 on 2023-02-28 17:50

import core_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0017_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core_backend.models.CoreUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='extra',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
