# Generated by Django 4.0.8 on 2023-03-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0019_booking_created_at_historicalbooking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core_backend.serviceroot'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='service_root',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.serviceroot'),
        ),
        migrations.AddField(
            model_name='service',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core_backend.serviceroot'),
        ),
    ]
