# Generated by Django 4.0.8 on 2023-03-22 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0019_booking_created_at_historicalbooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovider',
            name='certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='contract_type',
            field=models.CharField(choices=[('CR', 'Contractor'), ('SR', 'Salaried')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='minimum_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='payment_account',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='payment_account_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='payment_routing',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='payment_via',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='provider',
            name='contract_type',
            field=models.CharField(choices=[('CR', 'Contractor'), ('SR', 'Salaried')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='provider',
            name='minimum_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_account',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_account_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_routing',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='payment_via',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='bill_min_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Defines the minimum that the provider will charge for this service', max_digits=32, verbose_name='billing minimum payment'),
        ),
        migrations.AddField(
            model_name='service',
            name='bill_rate_type',
            field=models.CharField(blank=True, choices=[('FT', 'Flat'), ('PA', 'Per Assignation'), ('PH', 'Per Hours'), ('PM', 'Per Minutes'), ('QT', 'Quantity')], default='FT', help_text='Is the type of pricing model', max_length=2, verbose_name='billing rate type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bill_amount',
            field=models.PositiveIntegerField(default=1, help_text='Is how many `bill_rate_type` will get charged, ex: 3 hours, 15 mins, etc.', verbose_name='billing amount'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bill_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Is how much the provider charges per `bill_rate_type`', max_digits=32, verbose_name='billing rate'),
        ),
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='core_backend.category'),
        ),
    ]
