# Generated by Django 4.0.8 on 2023-03-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0021_historicalprovider_certifications_and_more'),
        ('core_backend', '0021_note'),
    ]

    operations = [
    ]
