# Generated by Django 4.0.5 on 2023-03-31 16:17

import core_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0022_merge_20230330_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='public_id',
            field=core_backend.fields.DailyUniqueIdentifierField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='public_id',
            field=core_backend.fields.DailyUniqueIdentifierField(max_length=30, null=True),
        ),
    ]
