# Generated by Django 4.0.8 on 2023-04-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0023_booking_public_id_historicalbooking_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='email context'),
        ),
        migrations.AddField(
            model_name='contact',
            name='fax_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='fax context'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='phone context'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='email_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='email context'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='fax_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='fax context'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='phone_context',
            field=models.CharField(blank=True, max_length=150, verbose_name='phone context'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='suffix',
            field=models.CharField(blank=True, max_length=150, verbose_name='suffix'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=150, verbose_name='suffix'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='title'),
        ),
    ]
