# Generated by Django 4.0.8 on 2023-04-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0024_contact_email_context_contact_fax_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core_backend.location'),
        ),
    ]
