# Generated by Django 4.1.7 on 2023-04-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0025_historicaluser_location_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='parent_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.company'),
        ),
    ]
