# Generated by Django 4.0.8 on 2023-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0025_historicaluser_location_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='unit_number',
            field=models.TextField(blank=True, null=True, verbose_name='unit number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='state or province'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.TextField(blank=True, null=True, verbose_name='ZIP code'),
        ),
    ]
