# Generated by Django 4.1.7 on 2023-04-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0026_company_parent_company_and_more'),
        ('core_backend', '0026_location_unit_number_alter_location_address_and_more'),
    ]

    operations = [
    ]
