# Generated by Django 4.0.8 on 2023-05-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0027_merge_20230426_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
