# Generated by Django 4.1.7 on 2023-05-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0028_note_last_updated_at_alter_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_as_payer', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='payer_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.company'),
        ),
    ]
