# Generated by Django 4.1.7 on 2023-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0028_note_last_updated_at_alter_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arrival date and time'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='types of appointments'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='arrive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arrival date and time'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='types of appointments'),
        ),
    ]
