# Generated by Django 4.1.7 on 2023-06-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0030_alter_historicalpayer_method_alter_payer_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categories',
        ),
        migrations.AddField(
            model_name='serviceroot',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='roots', to='core_backend.category'),
        ),
        migrations.AddField(
            model_name='serviceroot',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='serviceroot',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
    ]
