# Generated by Django 4.1.7 on 2023-06-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0030_alter_historicalpayer_method_alter_payer_method'),
        ('core_backend', '0031_event_arrive_at_event_description_and_more'),
    ]

    operations = [
    ]
