# Generated by Django 4.1.7 on 2023-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0031_remove_service_categories_serviceroot_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arrival date and time'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='arrive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arrival date and time'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
    ]
