# Generated by Django 4.1.7 on 2023-07-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0032_event_arrive_at_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAuthorization',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('contact_via', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('fax', 'fax')], max_length=32)),
                ('last_updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REFERRED', 'Referred')], default='PENDING', max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authorizer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.payer')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.company')),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical authorization',
                'verbose_name_plural': 'historical authorizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('contact_via', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('fax', 'fax')], max_length=32)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REFERRED', 'Referred')], default='PENDING', max_length=32)),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core_backend.payer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core_backend.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core_backend.contact')),
                ('events', models.ManyToManyField(related_name='authorizations', to='core_backend.event')),
            ],
            options={
                'verbose_name': 'authorization',
                'verbose_name_plural': 'authorizations',
            },
        ),
    ]
