# Generated by Django 4.1.7 on 2023-07-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0033_historicalauthorization_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core_backend.contact'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='contact_via',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('phone', 'phone'), ('fax', 'fax')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REFERRED', 'Referred'), ('OVERRIDE', 'Override')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalauthorization',
            name='contact_via',
            field=models.CharField(blank=True, choices=[('email', 'email'), ('phone', 'phone'), ('fax', 'fax')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthorization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REFERRED', 'Referred'), ('OVERRIDE', 'Override')], default='PENDING', max_length=32),
        ),
    ]
