# Generated by Django 4.0.5 on 2023-07-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0034_alter_authorization_contact_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set(),
        ),
    ]
