# Generated by Django 4.1.7 on 2023-07-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0035_alter_agent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core_backend.booking'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.booking'),
        ),
    ]
