# Generated by Django 4.1.7 on 2023-07-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0036_booking_parent_historicalbooking_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('alpha2', models.CharField(max_length=2, verbose_name='alpha2')),
                ('alpha3', models.CharField(max_length=3, verbose_name='alpha3')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('common', models.BooleanField(default=False, verbose_name='common')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLanguage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('alpha2', models.CharField(max_length=2, verbose_name='alpha2')),
                ('alpha3', models.CharField(max_length=3, verbose_name='alpha3')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('common', models.BooleanField(default=False, verbose_name='common')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical language',
                'verbose_name_plural': 'historical languages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
