# Generated by Django 4.1.7 on 2023-08-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0040_historicalserviceroot_historicalservice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-available', '-common', 'name'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
    ]
