# Generated by Django 4.0.8 on 2023-08-24 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0041_alter_language_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='Unreported', max_length=32)),
                ('arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('observations', models.TextField(blank=True, default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core_backend.event')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='Unreported', max_length=32)),
                ('arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('observations', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical report',
                'verbose_name_plural': 'historical reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
