# Generated by Django 4.1.7 on 2023-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0042_report_historicalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallanguage',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='alpha2'),
        ),
        migrations.AlterField(
            model_name='historicallanguage',
            name='alpha3',
            field=models.CharField(max_length=6, verbose_name='alpha3'),
        ),
        migrations.AlterField(
            model_name='language',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='alpha2'),
        ),
        migrations.AlterField(
            model_name='language',
            name='alpha3',
            field=models.CharField(max_length=6, verbose_name='alpha3'),
        ),
    ]
