# Generated by Django 4.0.5 on 2023-09-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0042_report_historicalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='operators', to='core_backend.company'),
        ),
    ]
