# Generated by Django 4.0.5 on 2023-09-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0043_alter_historicallanguage_alpha2_and_more'),
        ('core_backend', '0043_alter_operator_companies'),
    ]

    operations = [
    ]
