# Generated by Django 4.1.7 on 2023-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0044_merge_20230904_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='bill_no_show_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Defines the fee that the provider will charge if the service is not completed', max_digits=32, verbose_name='billing no show fee'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='bill_rate_minutes_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Defines the minimum amount of minutes that will count as a full hour if `bill_rate_type` is hourly', max_digits=32, null=True, verbose_name='billing minutes rate threshold'),
        ),
        migrations.AddField(
            model_name='service',
            name='bill_no_show_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Defines the fee that the provider will charge if the service is not completed', max_digits=32, verbose_name='billing no show fee'),
        ),
        migrations.AddField(
            model_name='service',
            name='bill_rate_minutes_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Defines the minimum amount of minutes that will count as a full hour if `bill_rate_type` is hourly', max_digits=32, null=True, verbose_name='billing minutes rate threshold'),
        ),
    ]
