# Generated by Django 4.1.7 on 2023-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0045_historicalservice_bill_no_show_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='public_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='public_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
