# Generated by Django 4.1.7 on 2023-09-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0046_alter_booking_public_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-common', 'name'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
    ]
