# Generated by Django 4.1.7 on 2023-09-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0047_alter_language_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceroot',
            options={'ordering': ['description'], 'verbose_name': 'service root', 'verbose_name_plural': 'service roots'},
        ),
    ]
