# Generated by Django 4.1.7 on 2023-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0048_alter_serviceroot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='expected_send_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalnotification',
            name='job_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalnotification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expected_send_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='job_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('SENT', 'Sent')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('SENT', 'Sent')], default='PENDING', max_length=32),
        ),
        migrations.CreateModel(
            name='ExternalApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expiration_timestamp', models.IntegerField()),
                ('scope', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'external API token',
                'verbose_name_plural': 'external API tokens',
                'unique_together': {('api_name', 'client_id')},
            },
        ),
    ]
