# Generated by Django 4.1.7 on 2023-09-26 20:36

from django.db import migrations, models


def create_group_and_permission(apps, schema_editor):
    from django.contrib.auth.models import Permission, Group
    from django.contrib.contenttypes.models import ContentType
    from core_backend.models import User

    content_type = ContentType.objects.get_for_model(User)
    permission, _ = Permission.objects.get_or_create(
        codename='can_push_fax_notifications',
        name='Can push fax notifications',
        content_type=content_type,
    )

    group, created = Group.objects.get_or_create(name='Fax Service Providers')
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0049_historicalnotification_expected_send_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
        migrations.RunPython(create_group_and_permission, migrations.RunPython.noop),
    ]
