# Generated by Django 4.1.7 on 2023-09-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0050_notification_status_message_and_fax_receiver_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='booking_to_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.booking'),
        ),
        migrations.AddField(
            model_name='note',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core_backend.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='booking_to_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core_backend.booking'),
        ),
    ]
