# Generated by Django 4.1.7 on 2023-10-03 14:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_backend', '0051_historicalnotification_booking_to_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='unique_field',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='unique_field',
            field=models.TextField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='UniqueCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_backend.business')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'unique condition',
                'verbose_name_plural': 'unique conditions',
                'unique_together': {('business', 'content_type')},
            },
        ),
    ]
