# Generated by Django 4.0.5 on 2023-10-11 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0052_event_unique_field_historicalevent_unique_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('country', models.TextField(blank=True, null=True, verbose_name='country')),
                ('state', models.TextField(blank=True, null=True, verbose_name='state or province')),
                ('county', models.TextField(blank=True, null=True, verbose_name='county')),
                ('city', models.TextField(blank=True, null=True, verbose_name='city')),
                ('zip', models.TextField(blank=True, null=True, verbose_name='ZIP code')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='core_backend.provider')),
            ],
            options={
                'verbose_name': 'service area',
                'verbose_name_plural': 'service areas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalServiceArea',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('country', models.TextField(blank=True, null=True, verbose_name='country')),
                ('state', models.TextField(blank=True, null=True, verbose_name='state or province')),
                ('county', models.TextField(blank=True, null=True, verbose_name='county')),
                ('city', models.TextField(blank=True, null=True, verbose_name='city')),
                ('zip', models.TextField(blank=True, null=True, verbose_name='ZIP code')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.provider')),
            ],
            options={
                'verbose_name': 'historical service area',
                'verbose_name_plural': 'historical service areas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
