# Generated by Django 4.1.7 on 2023-10-18 18:11
import json

from django.db import migrations, models


# Function to convert text to JSON
def convert_text_to_json(apps, schema_editor):
    Extra = apps.get_model('core_backend', 'Extra')
    for extra in Extra.objects.all():
        if not extra.value:
            continue

        try:
            # If value is already a JSON, leave it as is
            read_json = json.loads(extra.value)
            if isinstance(read_json, int):
                raise TypeError

            extra.data = extra.value

        except (json.JSONDecodeError, TypeError):
            # If it fails, it's not JSON, so convert the value to JSON
            extra.data = json.dumps(str(extra.value)) if isinstance(extra.value, int) else json.dumps(extra.value)
        extra.save()


# Function to convert JSON back to text
def revert_json_to_text(apps, schema_editor):
    Extra = apps.get_model('core_backend', 'Extra')
    for extra in Extra.objects.all():
        if not extra.data:
            continue

        # Convert JSON data back to a string format
        extra.value = str(json.loads(extra.data))
        extra.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0052_event_unique_field_historicalevent_unique_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='key',
            field=models.TextField(verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='value',
            field=models.TextField(verbose_name='value', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.RunPython(
            code=convert_text_to_json,
            reverse_code=revert_json_to_text,
        ),
        migrations.RemoveField(
            model_name='extra',
            name='value',
        ),
        migrations.AlterField(
            model_name='extra',
            name='data',
            field=models.JSONField(verbose_name='data'),
        ),
    ]
