# Generated by Django 4.1.7 on 2023-10-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0053_extra_switch_to_json_rename_value_to_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprovider',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='certifications',
        ),
    ]
