# Generated by Django 4.0.5 on 2023-10-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0053_servicearea_historicalservicearea'),
        ('core_backend', '0055_migrate_language_extras_from_id_to_alpha3'),
    ]

    operations = [
    ]
