# Generated by Django 4.0.8 on 2023-11-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0056_merge_20231025_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['recipient__user__first_name', 'recipient__user__last_name'], 'verbose_name': 'affiliation', 'verbose_name_plural': 'affiliations'},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'provider data', 'verbose_name_plural': 'provider data'},
        ),
        migrations.AlterModelOptions(
            name='requester',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'requester data', 'verbose_name_plural': 'requester data'},
        ),
    ]
