# Generated by Django 4.1.10 on 2023-11-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0057_alter_affiliation_options_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agents_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='operators_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payers_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='providers_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='recipients_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requesters_companies',
        ),
    ]
