# Generated by Django 4.1.10 on 2023-11-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0057_remove_booking_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agents_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='operators_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payers_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='providers_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='recipients_companies',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requesters_companies',
        ),
    ]
