# Generated by Django 4.1.7 on 2024-02-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0058_remove_booking_agents_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreport',
            name='status',
            field=models.CharField(default='Unreported', max_length=128),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='Unreported', max_length=128),
        ),
    ]
