# Generated by Django 4.1.7 on 2024-02-20 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0059_alter_historicalreport_status_alter_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompanyRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('bill_amount', models.PositiveIntegerField(default=1, help_text='Is how many `bill_rate_type` will get charged, ex: 3 hours, 15 mins, etc.', verbose_name='billing amount')),
                ('bill_rate_type', models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('PER_ASSIGNATION', 'Per Assignation'), ('PER_HOURS', 'Per Hours'), ('PER_MINUTES', 'Per Minutes'), ('QUANTITY', 'Quantity')], default='FLAT', help_text='Is the type of pricing model', max_length=255, verbose_name='billing rate type')),
                ('bill_min_payment', models.DecimalField(decimal_places=2, default=0, help_text='Defines the minimum that the provider will charge for this service', max_digits=32, verbose_name='billing minimum payment')),
                ('bill_no_show_fee', models.DecimalField(decimal_places=2, default=0, help_text='Defines the fee that the provider will charge if the service is not completed', max_digits=32, verbose_name='billing no show fee')),
                ('bill_rate', models.DecimalField(decimal_places=2, default=0, help_text='Is how much the provider charges per `bill_rate_type`', max_digits=32, verbose_name='billing rate')),
                ('bill_rate_minutes_threshold', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Defines the minimum amount of minutes that will count as a full hour if `bill_rate_type` is hourly', max_digits=32, null=True, verbose_name='billing minutes rate threshold')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.business')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.serviceroot')),
            ],
            options={
                'verbose_name': 'historical company rate',
                'verbose_name_plural': 'historical company rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('bill_amount', models.PositiveIntegerField(default=1, help_text='Is how many `bill_rate_type` will get charged, ex: 3 hours, 15 mins, etc.', verbose_name='billing amount')),
                ('bill_rate_type', models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('PER_ASSIGNATION', 'Per Assignation'), ('PER_HOURS', 'Per Hours'), ('PER_MINUTES', 'Per Minutes'), ('QUANTITY', 'Quantity')], default='FLAT', help_text='Is the type of pricing model', max_length=255, verbose_name='billing rate type')),
                ('bill_min_payment', models.DecimalField(decimal_places=2, default=0, help_text='Defines the minimum that the provider will charge for this service', max_digits=32, verbose_name='billing minimum payment')),
                ('bill_no_show_fee', models.DecimalField(decimal_places=2, default=0, help_text='Defines the fee that the provider will charge if the service is not completed', max_digits=32, verbose_name='billing no show fee')),
                ('bill_rate', models.DecimalField(decimal_places=2, default=0, help_text='Is how much the provider charges per `bill_rate_type`', max_digits=32, verbose_name='billing rate')),
                ('bill_rate_minutes_threshold', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Defines the minimum amount of minutes that will count as a full hour if `bill_rate_type` is hourly', max_digits=32, null=True, verbose_name='billing minutes rate threshold')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rates', to='core_backend.business')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rates', to='core_backend.company')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_rates', to='core_backend.serviceroot')),
            ],
            options={
                'verbose_name': 'company rate',
                'verbose_name_plural': 'company rates',
            },
        ),
    ]
