# Generated by Django 4.1.7 on 2024-02-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0059_preferredagency_historicalpreferredagency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('relationship', models.TextField(blank=True, null=True, verbose_name='relationship')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_relationships', to='core_backend.company')),
            ],
            options={
                'verbose_name': 'company relationship',
                'verbose_name_plural': 'company relationships',
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalPreferredAgency',
            new_name='HistoricalCompanyRelationship',
        ),
        migrations.AlterModelOptions(
            name='historicalcompanyrelationship',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical company relationship', 'verbose_name_plural': 'historical company relationships'},
        ),
        migrations.DeleteModel(
            name='PreferredAgency',
        ),
    ]
