# Generated by Django 4.1.7 on 2024-03-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0060_company_relationships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='relationships',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='core_backend.companyrelationship'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='relationships',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.companyrelationship'),
        ),
    ]
