# Generated by Django 4.1.7 on 2024-03-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0060_historicalcompanyrate_companyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrate',
            name='business',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyrate',
            name='business',
        ),
    ]
