# Generated by Django 4.1.7 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0061_alter_company_relationships_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcompany',
            name='relationships',
        ),
        migrations.RemoveField(
            model_name='company',
            name='relationships',
        ),
        migrations.AddField(
            model_name='company',
            name='relationships',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_companies', to='core_backend.companyrelationship'),
        ),
    ]
