# Generated by Django 4.1.7 on 2024-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0061_remove_companyrate_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrate',
            name='language',
            field=models.CharField(blank=True, default=None, help_text='Defines the language that the provider will charge for this service', max_length=255, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='historicalcompanyrate',
            name='language',
            field=models.CharField(blank=True, default=None, help_text='Defines the language that the provider will charge for this service', max_length=255, null=True, verbose_name='language'),
        ),
    ]
