# Generated by Django 4.1.7 on 2024-03-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0062_companyrate_language_historicalcompanyrate_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGlobalSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.CharField(blank=True, max_length=128, verbose_name='client')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical global setting',
                'verbose_name_plural': 'historical global settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.CharField(blank=True, max_length=128, verbose_name='client')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='core_backend.business')),
            ],
            options={
                'verbose_name': 'global setting',
                'verbose_name_plural': 'global settings',
            },
        ),
    ]
