# Generated by Django 4.1.7 on 2024-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0062_remove_historicalcompany_relationships_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='relationships',
            new_name='company_relationships',
        ),
    ]
