# Generated by Django 4.1.7 on 2024-03-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0063_alter_company_parent_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_relationships',
        ),
    ]
