# Generated by Django 4.1.7 on 2024-03-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0064_remove_company_company_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelationship',
            name='company_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_relationships_from', to='core_backend.company'),
        ),
        migrations.AlterField(
            model_name='companyrelationship',
            name='company_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_relationships_to', to='core_backend.company'),
        ),
    ]
