# Generated by Django 4.1.7 on 2024-04-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0066_historicaladmin_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
