# Generated by Django 4.1.7 on 2024-04-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0067_alter_companyrate_bill_min_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='language',
        ),
        migrations.AddField(
            model_name='historicalrate',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='historicalrate',
            name='global_setting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.globalsetting'),
        ),
        migrations.AddField(
            model_name='rate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core_backend.company'),
        ),
        migrations.AddField(
            model_name='rate',
            name='global_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core_backend.globalsetting'),
        ),
    ]
