# Generated by Django 4.1.7 on 2024-05-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0068_alter_companyrate_bill_min_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
