# Generated by Django 4.1.7 on 2024-04-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0068_alter_companyrate_bill_min_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcompanyrate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyrate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyrate',
            name='root',
        ),
        migrations.DeleteModel(
            name='CompanyRate',
        ),
        migrations.DeleteModel(
            name='HistoricalCompanyRate',
        ),
    ]
