# Generated by Django 4.1.7 on 2024-07-23 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0070_alter_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrate',
            name='bill_amount',
            field=models.FloatField(default=1, help_text='Is how many `bill_rate_type` will get charged, ex: 3 hours, 15 mins, etc.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='billing amount'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='bill_amount',
            field=models.FloatField(default=1, help_text='Is how many `bill_rate_type` will get charged, ex: 3 hours, 15 mins, etc.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='billing amount'),
        ),
    ]
