# Generated by Django 4.1.7 on 2024-08-12 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0071_alter_historicalrate_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, null=True, size=None),
        ),
    ]
