# Generated by Django 4.1.7 on 2024-08-12 19:19

from django.db import migrations

def fill_default_aliases(apps, schema_editor):
    Company = apps.get_model('core_backend', 'Company')
    for company in Company.objects.all():
        if company.aliases is None:
            company.aliases = []
            company.save()

    User = apps.get_model('core_backend', 'User')
    for user in User.objects.all():
        if user.aliases is None:
            user.aliases = []
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0072_company_aliases_historicalcompany_aliases_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_default_aliases)
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0072_company_aliases_historicalcompany_aliases_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_default_aliases)
    ]
