# Generated by Django 4.1.13 on 2025-02-12 18:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0074_invoice_amount_invoice_created_at_invoice_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US', verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US', verbose_name='phone number'),
        ),
    ]
