# Generated by Django 4.1.13 on 2025-02-24 20:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0075_alter_contact_phone_alter_historicalcontact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('confirmation_receiver', models.CharField(max_length=128)),
                ('interpreter', models.BooleanField(default=False)),
                ('interpreter_receiver', models.CharField(max_length=128)),
                ('report', models.BooleanField(default=False)),
                ('report_frecuency', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None), size=None)),
                ('report_range', models.CharField(choices=[('ALL', 'All'), ('FOURTEEN_DAYS', 'Fourteen_days'), ('SEVEN_DAYS', 'Seven_days'), ('THREE_DAYS', 'Three_days'), ('ONE_DAY', 'One_day'), ('Today', 'Today')], default='SEVEN_DAYS', max_length=32)),
                ('report_receiver', models.CharField(max_length=128)),
                ('last_report_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_options', to='core_backend.company')),
            ],
        ),
    ]
