# Generated by Django 4.1.13 on 2025-02-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0076_invoice_is_deleted_historicalinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core_backend.event'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('SENT', 'Sent'), ('IN REVIEW', 'In Review'), ('PAID', 'Paid')], default='IN REVIEW', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core_backend.event'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('SENT', 'Sent'), ('IN REVIEW', 'In Review'), ('PAID', 'Paid')], default='IN REVIEW', max_length=32),
        ),
    ]
