# Generated by Django 4.1.13 on 2025-04-09 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0079_alter_report_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationoption',
            name='report_frecuency',
        ),
        migrations.AddField(
            model_name='notificationoption',
            name='report_frequency',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='confirmation_receiver',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='interpreter_change_receiver',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='report_range',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Fourteen days', 'Fourteen Days'), ('Seven days', 'Seven Days'), ('Three days', 'Three Days'), ('One day', 'One Day'), ('Today', 'Today')], default='Seven days', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='report_receiver',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
